# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: 'admin@example.com',  password: 'secret123', admin: true,  name: 'admin',  active: true)
User.create(email: 'leslie@example.com', password: 'secret123', admin: false, name: 'leslie', active: true)
User.create(email: 'dwan@example.com',   password: 'secret123', admin: false, name: 'dwan',   active: true)

Setting.create(
email: 'inquiries@rosewoodresidence.com',
address: 'Gov M Cuenco Avenue, Cebu City',
page_description: 'To check for room availability, schedule a room inspection or for other inquiries, please fill in the form and we will get back to you as soon as we can!',
about_us: 'Rosewood Residence is committed to providing customers, particularly students, with an environment suitable for nurturing their growth and achievement. All our rooms are built and designed with the needs of a student in mind. Each room is proviided with ample cabinet and table space. Provisions for natural light to enter are installed across all rooms. Despite being fully airconditioned, residents may opt for fresh air as ventilation in between rooms is has been made top priority. With our comfortable rooms and convenient location, students now have the convenience of going back to their rooms in between classes.',
why_us_1: 'Free wi-fi is a main consideration for students choosing accomodations. We have provided free wi-fi for all residents at no additonal cost, so you do not need to  go through the trouble of applying for a connection yourself',
why_us_2: 'All rooms are provided with private ensuite bathrooms so you do not have to go down the hall to take a bath or to use the toilet.',
why_us_3: 'Privacy and security are our top priorities. Only registered residents are allowed inside Rosewood Residence premises. In addition to that, 24-7 security and cctv systems are installed at all public areas.',
user_id:  1
)


Faq.create(question: 'Are rooms equipped with a telephone line?', answer: 'Sorry, rooms are not equipped with a fixed telephone line. However, we have a pay phone at the lobby. However, most of our residents prefer using their for their communication needs.', user_id: 1)
Faq.create(question: 'Are rooms furnished?', answer: 'All rooms are provided with beds and mattresses. Ample cabinet and table space is also installed.', user_id: 1)
Faq.create(question: 'Are rooms equipped with air conditioners?', answer: 'Yes, each room is equipped with an air conditioner.', user_id: 1)
Faq.create(question: 'What kind of documents do I need to sign a lease agreement?', answer: 'For local residents, we will a government id aside from your current school id. For foreign students, we will require your passport and your current school id.', user_id: 1)
Faq.create(question: 'How long is the minimum rental term?', answer: 'Minimum lease term is one semester. That would be June to October, November to March or April to May.', user_id: 1)
Faq.create(question: 'Can I arrange for a room viewing?', answer: 'Sure, please contact us so we can set a schedule for inspection.', user_id: 1)
Faq.create(question: 'What else do I have to pay?', answer: 'We will require a deposit of one month. This will be refunded if the room is left free of damages. else actual cost of repairs will be taken from the deposit. Aside from the monthly rental, electricity and water consumption will also be charged.', user_id: 1)
Faq.create(question: 'Are meals included in the rent?', answer: 'No, unfortunately meals are not included as of this time.', user_id: 1)
Faq.create(question: 'Will I be allowed to share the room with a friend or family member who will be in town for a few days?', user_id: 1)
Faq.create(question: 'Is there a building curfew?', user_id: 1)
Faq.create(question: 'Can I smoke in the room?', answer: 'Smoking is prohibited in the rooms, bathroom, and all areas of the building. Smoking in outside the building is also not allowed as Cebu City has an anti-smoking ordinance in place.', user_id: 1)
Faq.create(question: 'Do I need to inform Rosewood Residence before I move out?', answer: 'If you wish to move out, we require at least 1 month advance notice. Notice must be given by completing out "Move Out Request Form and submitting it to our office.', user_id: 1)
Faq.create(question: 'How soon do I need to inform  Rosewood Residence that I plan to move out?', answer: 'A minimum of 1 month advance notice is required if you wish to move out. Please be informed that if the 1 month advance notice is not given, a 1 month rent will still be charged from the day that we are informed.', user_id: 1)
Faq.create(question: 'When is the monthly cut off date?', answer: '', user_id: 1)
Faq.create(question: 'Can I ask for an extra bed?', answer: 'Our rooms are specifically made for those who want more comfort and convenience. If the number of persons in your group exceed the room limit, we will be happy provide you with more rooms.', user_id: 1)


Room.create(room_no: 101, max_occupants: 2, room_rate: 8000, active: false, user_id: 1)
Room.create(room_no: 102, max_occupants: 4, room_rate: 12000, active: true, user_id: 1)

Room.create(room_no: 201, max_occupants: 3, room_rate: 10500, active: true, user_id: 1)
Room.create(room_no: 202, max_occupants: 3, room_rate: 10000, active: true, user_id: 1)
Room.create(room_no: 203, max_occupants: 3, room_rate: 9000, active: true,  user_id: 1)
Room.create(room_no: 204, max_occupants: 2, room_rate: 8500, active: true,  user_id: 1)
Room.create(room_no: 205, max_occupants: 2, room_rate: 8000, active: true,  user_id: 1)
Room.create(room_no: 206, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 207, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 208, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 209, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 210, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 211, max_occupants: 2, room_rate: 8000, active: true,  user_id: 1)
Room.create(room_no: 212, max_occupants: 3, room_rate: 11500, active: true, user_id: 1)

Room.create(room_no: 301, max_occupants: 3, room_rate: 13000, active: true, user_id: 1)
Room.create(room_no: 302, max_occupants: 3, room_rate: 9500, active: true, user_id: 1)
Room.create(room_no: 303, max_occupants: 3, room_rate: 9500, active: true,  user_id: 1)
Room.create(room_no: 304, max_occupants: 2, room_rate: 8500, active: true,  user_id: 1)
Room.create(room_no: 305, max_occupants: 2, room_rate: 8500, active: true,  user_id: 1)
Room.create(room_no: 306, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 307, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 308, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 309, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 310, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 311, max_occupants: 2, room_rate: 8000, active: true,  user_id: 1)
Room.create(room_no: 312, max_occupants: 3, room_rate: 11500, active: true, user_id: 1)

Room.create(room_no: 401, max_occupants: 3, room_rate: 10000, active: true, user_id: 1)
Room.create(room_no: 402, max_occupants: 3, room_rate: 9000, active: true,  user_id: 1)
Room.create(room_no: 403, max_occupants: 3, room_rate: 8500, active: true,  user_id: 1)
Room.create(room_no: 404, max_occupants: 2, room_rate: 8000, active: true,  user_id: 1)
Room.create(room_no: 405, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 406, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 407, max_occupants: 2, room_rate: 7000, active: true,  user_id: 1)
Room.create(room_no: 408, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 409, max_occupants: 2, room_rate: 7000, active: true,  user_id: 1)
Room.create(room_no: 410, max_occupants: 2, room_rate: 7500, active: true,  user_id: 1)
Room.create(room_no: 411, max_occupants: 2, room_rate: 75000, active: true, user_id: 1)
Room.create(room_no: 412, max_occupants: 3, room_rate: 10500, active: true, user_id: 1)

Utility.create(name: ROOM_RATE,   category: 'Basic', sort_order: 1, user_id: 1)
Utility.create(name: ELECTRICITY, category: 'Basic', sort_order: 2, description: "Monthly. Per kilowatt hour",    first_limit: 0, first_rate: 12, excess_rate: 0, unit: 'per kwh', user_id: 1)
Utility.create(name: WATER_MIN,   category: 'Basic', sort_order: 3, description: "Monthly. First 10 cubic meter", first_limit: 10,first_rate: 150, excess_rate: 20, unit: 'per cubic meter', user_id: 1)
Utility.create(name: WATER_EXCESS,category: 'Basic', sort_order: 4, description: "Monthly. Excess after 10 cubic meter", first_limit: 10,first_rate: 20, excess_rate: 20, unit: 'per cubic meter', user_id: 1)
Utility.create(name: 'Cable TV Subscription', category: 'Extra', sort_order: 5, description: "Monthly fee",  first_rate: 450, unit: 'per month', user_id: 1)
Utility.create(name: 'Cable TV Installation', category: 'Extra', sort_order: 6, description: "One time fee", first_rate: 450, unit: 'one time',  user_id: 1)
Utility.create(name: 'Cable TV Termination',  category: 'Extra', sort_order: 7, description: "One time fee", first_rate: 450, unit: 'one time',  user_id: 1)

Utility.create(name: 'Parking Fee',    category: 'Extra', sort_order: 8, description: "Monthly parking fee",    first_rate: 1500,       unit: 'per month', user_id: 1)
Utility.create(name: 'Transcient Fee', category: 'Extra', sort_order: 9, description: "Extra person per night", first_rate: 250,        unit: 'per night', user_id: 1)
Utility.create(name: 'Penalty',        category: 'Extra', sort_order: 10, description: "Past due penalty",       first_rate: 100,        unit: 'per day',   user_id: 1)
Utility.create(name: 'Damages',        category: 'Extra', sort_order: 11, description: "Rate depending on damage",                       unit: 'per damage',user_id: 1)
Utility.create(name: 'Cleaning Fee',   category: 'Extra', sort_order: 12, description: "Out-of-cycle cleaning request", first_rate: 350, unit: 'per room',  user_id: 1)
Utility.create(name: 'Lost Key',       category: 'Extra', sort_order: 13, description: "",                       first_rate: 150,        unit: 'per key',   user_id: 1)
Utility.create(name: 'Locked Out',     category: 'Extra', sort_order: 14, description: "lock out penalty",       first_rate: 50,         unit: 'per instance',user_id: 1)


Occupant.create(first_name: 'Roche', last_name: 'Doruelo', user_id: 1)
Occupant.create(first_name: 'Asvatha', last_name: 'Karthikeyan', user_id: 1)
Occupant.create(first_name: 'Sathiyapriya', last_name: 'Sivakumar', user_id: 1)
Occupant.create(first_name: 'Hazel Olive', last_name: 'Parmes', user_id: 1)
Occupant.create(first_name: 'Rheina', last_name: 'Retana', user_id: 1)
Occupant.create(first_name: 'Roche', last_name: 'Ompad', user_id: 1)

Occupant.create(first_name: 'Loren Grace', last_name: 'Manigos', user_id: 1)
Occupant.create(first_name: 'Annikka Felicitty', last_name: 'Balaga', user_id: 1)
Occupant.create(first_name: 'Charlemagne', last_name: 'Hoppe', user_id: 1)
Occupant.create(first_name: 'Erika Mae', last_name: 'Alingalan', user_id: 1)
Occupant.create(first_name: 'Julia', last_name: 'Jubag', user_id: 1)
Occupant.create(first_name: 'Christine Hace', last_name: 'Escabarte', user_id: 1)
Occupant.create(first_name: 'Jasmine Czarina', last_name: 'Chua', user_id: 1)
Occupant.create(first_name: 'Mika Ella', last_name: 'Plaza', user_id: 1)
Occupant.create(first_name: 'Aleisha Merryl', last_name: 'Escobia', user_id: 1)
Occupant.create(first_name: 'Evangeryl', last_name: 'Munez', user_id: 1)
Occupant.create(first_name: 'Dawn Krista', last_name: 'Sosobrado', user_id: 1)
Occupant.create(first_name: 'April Chiara', last_name: 'Sosobrado', user_id: 1)
Occupant.create(first_name: 'Kei Jaya', last_name: 'Pintar', user_id: 1)
Occupant.create(first_name: 'Kaye', last_name: 'Rojas', user_id: 1)
Occupant.create(first_name: 'Janna Faye Marie', last_name: 'Magrina', user_id: 1)
Occupant.create(first_name: 'Sarah', last_name: 'Hartman', user_id: 1)
Occupant.create(first_name: 'Bianca Louise', last_name: 'Abatol', user_id: 1)
Occupant.create(first_name: 'Caryl', last_name: 'Literal', user_id: 1)
Occupant.create(first_name: 'Arnne Leigh Basle', last_name: 'Fano', user_id: 1)
Occupant.create(first_name: 'Eren Kate', last_name: 'Javellana', user_id: 1)
Occupant.create(first_name: 'Frauline', last_name: 'Darejo', user_id: 1)
Occupant.create(first_name: 'Jayhan Fe', last_name: 'Bornea', user_id: 1)
Occupant.create(first_name: 'Aira Marie', last_name: 'Rizon', user_id: 1)
Occupant.create(first_name: 'Camille', last_name: 'Dela Cruz', user_id: 1)
Occupant.create(first_name: 'Kim Sherri', last_name: 'Dela Cruz', user_id: 1)
Occupant.create(first_name: 'Nikkae', last_name: 'Angob', user_id: 1)
Occupant.create(first_name: 'Miela Grace', last_name: 'Ronulo', user_id: 1)
Occupant.create(first_name: 'Svetlana Yadhira', last_name: 'Agote', user_id: 1)
Occupant.create(first_name: 'Jermaine Nicole', last_name: 'Cabantan', user_id: 1)
Occupant.create(first_name: 'Dara Jireh', last_name: 'Tingal', user_id: 1)
Occupant.create(first_name: 'Dione Monique', last_name: 'Longos', user_id: 1)
Occupant.create(first_name: 'Claire Angela', last_name: 'Carias', user_id: 1)
Occupant.create(first_name: 'Christin Faye', last_name: 'Caybot', user_id: 1)
Occupant.create(first_name: 'Apple Rose', last_name: 'Magallano', user_id: 1)
Occupant.create(first_name: 'Kriselda', last_name: 'Inferido', user_id: 1)
Occupant.create(first_name: 'Karina', last_name: 'Inferido', user_id: 1)
Occupant.create(first_name: 'Keanna', last_name: 'Inferido', user_id: 1)
Occupant.create(first_name: 'Isabela', last_name: 'Lee', user_id: 1)
Occupant.create(first_name: 'Matthew David', last_name: 'Lee', user_id: 1)
Occupant.create(first_name: 'Irish Gem', last_name: 'Soliva', user_id: 1)
Occupant.create(first_name: 'Marian Jebryl', last_name: 'Dacalos', user_id: 1)
Occupant.create(first_name: 'Orlymae', last_name: 'Vinculado', user_id: 1)
Occupant.create(first_name: 'Astrid', last_name: 'Buenafe', user_id: 1)
Occupant.create(first_name: 'Jessamaine', last_name: 'Tangoan', user_id: 1)
Occupant.create(first_name: 'Eiza Mahal', last_name: 'Rivera', user_id: 1)
Occupant.create(first_name: 'Maileen', last_name: 'Rivera', user_id: 1)
Occupant.create(first_name: 'Razel Gay', last_name: 'Bonita', user_id: 1)
Occupant.create(first_name: 'Rena Gay', last_name: 'Bonita', user_id: 1)
Occupant.create(first_name: 'Chledaugh Shekinah', last_name: 'Galvez', user_id: 1)
Occupant.create(first_name: 'Rhea Bernice', last_name: 'Alea', user_id: 1)
Occupant.create(first_name: 'Berna', last_name: 'Alea', user_id: 1)
Occupant.create(first_name: 'Kimberly Mae', last_name: 'Liu', user_id: 1)
Occupant.create(first_name: 'Gay Louise', last_name: 'De Castro', user_id: 1)
Occupant.create(first_name: 'Estelle', last_name: 'Ocampo', user_id: 1)
Occupant.create(first_name: 'Emmanuelle', last_name: 'Ocampo', user_id: 1)
Occupant.create(first_name: 'Julia Gabrielle', last_name: 'Laurente', user_id: 1)
Occupant.create(first_name: 'Ma. Shannelle Gwyneth', last_name: 'Moncado', user_id: 1)
